1. Import Libraries

In [7]:
import pandas as pd
import numpy as np
import re
from IPython.display import display

2. Menghubungkan Google Drive

In [8]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

3. Memuat Data Penjualan yang Belum Bersih

In [12]:
file_path = '/content/drive/MyDrive/Colab Notebooks/Data kotor penjualan baju distro.xlsx'

data = pd.read_excel(
    file_path,
    sheet_name='Data Kotor',
    engine='openpyxl'
)

print("DATA PENJUALAN BAJU DISTRO")
display(data)

DATA PENJUALAN BAJU DISTRO

,No,Nama Produk,Warna,Ukuran,Harga (Rp),Jumlah Terjual,Tanggal,Status Pembayaran,Metode Penjualan
0,1,Kaos Oversize,Hitam,M,75000.0,12,02/01/2026,Lunas,Online
1,2,Kaos Oversize,putih,L,75000.0,8,03-01-2026,lunas,Offline
2,3,Hoodie Basic,Abu-abu,XL,125000.0,5,2026/01/04,Belum,Online
3,4,Kemeja Flanel,Merah,L,110000.0,7,05 Jan 2026,Lunas,offline
4,5,Kaos Graphic,Hitam,M,85000.0,15,06/01/26,Lunas,Online
5,6,Crewneck,Navy,L,135000.0,6,07-01-2026,belum lunas,Online
6,7,Celana Cargo,Cream,32,150000.0,4,08/01/2026,Lunas,Offline
7,8,Kaos Oversize,Hitam,m,75000.0,10,09/01/2026,Lunas,online
8,9,Hoodie Basic,Hitam,XXL,125000.0,3,10-01-2026,Belum,Offline
9,10,Kemeja Flanel,biru,M,110000.0,9,11/01/2026,Lunas,Online
10,11,Kaos Graphic,Putih,L,85000.0,11,12 Jan 2026,LUNAS,Online
11,12,Crewneck,Navy,XL,135000.0,7,13/01/2026,Belum,Offline
12,13,Celana Cargo,Hitam,30,150000.0,5,14-01-2026,Lunas,online
13,14,Kaos Oversize,PUTIH,XL,75000.0,14,15/01/2026,Lunas,Offline
14,15,Hoodie Basic,abu-abu,L,125000.0,6,16/01/2026,Belum,Online
15,16,Kemeja Flanel,Hijau,M,110000.0,8,17-01-2026,Lunas,Offline
16,17,Kaos Graphic,Hitam,XL,85000.0,13,18/01/2026,Lunas,Online
17,18,Crewneck,Navy,m,135000.0,4,19 Jan 2026,belum,Online
18,19,Celana Cargo,Cream,34,150000.0,3,20/01/26,Lunas,offline
19,20,Kaos Oversize,Hitam,L,75000.0,9,21-01-2026,Lunas,Online
20,21,Hoodie Basic,Hitam,M,125.0,5,22/01/2026,Belum,Offline
21,22,Kemeja Flanel,Merah,XL,110000.0,6,23/01/2026,Lunas,online
22,23,Kaos Graphic,Putih,M,85000.0,12,24-01-2026,Lunas,Online
23,24,Crewneck,Navy,L,135000.0,5,25/01/2026,BELUM,Offline
24,25,Celana Cargo,Hitam,32,150000.0,7,26 Jan 2026,Lunas,Online
25,26,Kaos Oversize,hitam,XL,75000.0,16,27/01/2026,Lunas,offline
26,27,Hoodie Basic,Abu abu,L,125000.0,4,28-01-2026,Belum,Online
27,28,Kemeja Flanel,Biru,M,110000.0,10,29/01/2026,Lunas,Online
28,29,Kaos Graphic,hitam,L,85000.0,9,30/01/2026,Lunas,Offline
29,30,Crewneck,NAVY,XL,135000.0,6,31-01-2026,belum lunas,Online
30,31,Kaos Oversize,Putih,NaN,75000.0,8,32/01/2026,Lunas,Online
31,32,Hoodie Basic,Hitam,M,-125000.0,2,01/02/2026,Belum,Offline
32,33,Kaos Graphic,Hitam,L,85000.0,sepuluh,02/02/2026,Lunas,Online
33,34,Celana Cargo,Cream,32,150000.0,0,03/02/2026,Lunas,Offline
34,35,Kemeja Flanel,Merah,L,110000.0,5,NaN,Lunas,Online

4. Melihat Informasi Dataset

In [13]:
print("\nInformasi Dataset:")
data.info()

print("\nJenis Data Setiap Kolom:")
print(data.dtypes)

Informasi Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No                 35 non-null     int64
 1   Nama Produk        35 non-null     object
 2   Warna              35 non-null     object
 3   Ukuran             34 non-null     object
 4   Harga (Rp)         35 non-null     float64
 5   Jumlah Terjual     35 non-null     object
 6   Tanggal            34 non-null     object
 7   Status Pembayaran  35 non-null     object
 8   Metode Penjualan   35 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 2.6+ KB

Jenis Data Setiap Kolom:
No                     int64
Nama Produk           object
Warna                 object
Ukuran                object
Harga (Rp)           float64
Jumlah Terjual        object
Tanggal               object
Status Pembayaran     object
Metode Penjualan      object
dtype: object

5. Merapikan Nama Produk

In [14]:
def rapikan_produk(product):
    if pd.isna(product):
        return np.nan

    product = str(product).strip()
    product = re.sub(r'\s+', ' ', product)
    product = product.title()

    return product


data['Produk Bersih'] = data['Nama Produk'].apply(rapikan_produk)

print("\nPerbandingan Nama Produk:")
display(data[['Nama Produk', 'Produk Bersih']].head(15))

Perbandingan Nama Produk:

      Nama Produk  Produk Bersih
0   Kaos Oversize  Kaos Oversize
1   Kaos Oversize  Kaos Oversize
2    Hoodie Basic   Hoodie Basic
3   Kemeja Flanel  Kemeja Flanel
4    Kaos Graphic   Kaos Graphic
5        Crewneck       Crewneck
6    Celana Cargo   Celana Cargo
7   Kaos Oversize  Kaos Oversize
8    Hoodie Basic   Hoodie Basic
9   Kemeja Flanel  Kemeja Flanel
10   Kaos Graphic   Kaos Graphic
11       Crewneck       Crewneck
12   Celana Cargo   Celana Cargo
13  Kaos Oversize  Kaos Oversize
14   Hoodie Basic   Hoodie Basic

6. Menyeragamkan Penulisan Warna

In [15]:
def rapikan_warna(color):
    if pd.isna(color):
        return np.nan

    color = str(color).strip().lower()
    color = re.sub(r'\s+', ' ', color)

    if color in ['abu abu', 'abu-abu']:
        return 'Abu-abu'

    return color.title()


data['Warna Bersih'] = data['Warna'].apply(rapikan_warna)

print("\nPerbandingan Data Warna:")
display(data[['Warna', 'Warna Bersih']].head(15))

Perbandingan Data Warna:

      Warna Warna Bersih
0     Hitam        Hitam
1     putih        Putih
2   Abu-abu      Abu-abu
3     Merah        Merah
4     Hitam        Hitam
5      Navy         Navy
6     Cream        Cream
7    Hitam         Hitam
8     Hitam        Hitam
9      biru         Biru
10    Putih        Putih
11     Navy         Navy
12    Hitam        Hitam
13    PUTIH        Putih
14  abu-abu      Abu-abu

7. Memperbaiki Format Ukuran Pakaian

In [16]:
def rapikan_ukuran(size):
    if pd.isna(size):
        return np.nan

    size = str(size).strip().upper()

    return size


data['Ukuran Bersih'] = data['Ukuran'].apply(rapikan_ukuran)

print("\nPerbandingan Ukuran:")
display(data[['Ukuran', 'Ukuran Bersih']].head(15))

Perbandingan Ukuran:

   Ukuran Ukuran Bersih
0       M             M
1       L             L
2      XL            XL
3       L             L
4       M             M
5       L             L
6      32            32
7       m             M
8     XXL           XXL
9       M             M
10      L             L
11     XL            XL
12     30            30
13     XL            XL
14      L             L

8. Validasi Nilai Harga

In [17]:
def rapikan_harga(price):
    if pd.isna(price):
        return np.nan

    price = str(price).strip()
    price = price.replace('.', '').replace(',', '')

    try:
        price = float(price)

        if price <= 0:
            return np.nan

        return price

    except:
        return np.nan


data['Harga Bersih'] = data['Harga (Rp)'].apply(rapikan_harga)

print("\nPemeriksaan Harga:")
display(data[['Harga (Rp)', 'Harga Bersih']].head(15))

Pemeriksaan Harga:

    Harga (Rp)  Harga Bersih
0      75000.0      750000.0
1      75000.0      750000.0
2     125000.0     1250000.0
3     110000.0     1100000.0
4      85000.0      850000.0
5     135000.0     1350000.0
6     150000.0     1500000.0
7      75000.0      750000.0
8     125000.0     1250000.0
9     110000.0     1100000.0
10     85000.0      850000.0
11    135000.0     1350000.0
12    150000.0     1500000.0
13     75000.0      750000.0
14    125000.0     1250000.0

9. Mengoreksi Jumlah Produk Terjual

In [18]:
def rapikan_jumlah(quantity):
    if pd.isna(quantity):
        return np.nan

    quantity = str(quantity).strip().lower()

    angka = {
        'satu': 1,
        'dua': 2,
        'tiga': 3,
        'empat': 4,
        'lima': 5,
        'enam': 6,
        'tujuh': 7,
        'delapan': 8,
        'sembilan': 9,
        'sepuluh': 10
    }

    if quantity in angka:
        return angka[quantity]

    try:
        quantity = int(float(quantity))

        if quantity <= 0:
            return np.nan

        return quantity

    except:
        return np.nan


data['Jumlah Terjual Bersih'] = (
    data['Jumlah Terjual'].apply(rapikan_jumlah)
)

print("\nPerbandingan Jumlah Terjual:")
display(data[['Jumlah Terjual', 'Jumlah Terjual Bersih']].head(15))

Perbandingan Jumlah Terjual:

   Jumlah Terjual  Jumlah Terjual Bersih
0              12                   12.0
1               8                    8.0
2               5                    5.0
3               7                    7.0
4              15                   15.0
5               6                    6.0
6               4                    4.0
7              10                   10.0
8               3                    3.0
9               9                    9.0
10             11                   11.0
11              7                    7.0
12              5                    5.0
13             14                   14.0
14              6                    6.0

10. Menyesuaikan Format Tanggal

In [19]:
data['Tanggal Bersih'] = pd.to_datetime(
    data['Tanggal'],
    errors='coerce',
    dayfirst=True
)

print("\nPerbandingan Tanggal:")
display(data[['Tanggal', 'Tanggal Bersih']].head(15))

Perbandingan Tanggal:

        Tanggal Tanggal Bersih
0    02/01/2026     2026-01-02
1    03-01-2026            NaT
2    2026/01/04            NaT
3   05 Jan 2026            NaT
4      06/01/26            NaT
5    07-01-2026            NaT
6    08/01/2026     2026-01-08
7    09/01/2026     2026-01-09
8    10-01-2026            NaT
9    11/01/2026     2026-01-11
10  12 Jan 2026            NaT
11   13/01/2026     2026-01-13
12   14-01-2026            NaT
13   15/01/2026     2026-01-15
14   16/01/2026     2026-01-16

11. Menata Status Pembayaran

In [20]:
def rapikan_pembayaran(status):
    if pd.isna(status):
        return np.nan

    status = str(status).strip().lower()

    if status == 'lunas':
        return 'Lunas'

    elif status in ['belum', 'belum lunas']:
        return 'Belum Lunas'

    return np.nan


data['Pembayaran Bersih'] = (
    data['Status Pembayaran'].apply(rapikan_pembayaran)
)

print("\nPerbandingan Status Pembayaran:")
display(
    data[
        ['Status Pembayaran', 'Pembayaran Bersih']
    ].head(15)
)

Perbandingan Status Pembayaran:

   Status Pembayaran Pembayaran Bersih
0              Lunas             Lunas
1              lunas             Lunas
2              Belum       Belum Lunas
3              Lunas             Lunas
4              Lunas             Lunas
5        belum lunas       Belum Lunas
6              Lunas             Lunas
7              Lunas             Lunas
8              Belum       Belum Lunas
9              Lunas             Lunas
10             LUNAS             Lunas
11             Belum       Belum Lunas
12             Lunas             Lunas
13             Lunas             Lunas
14             Belum       Belum Lunas

12. Menyamakan Metode Penjualan

In [21]:
data['Metode Bersih'] = (
    data['Metode Penjualan']
    .astype('string')
    .str.strip()
    .str.lower()
    .str.title()
)

print("\nPerbandingan Metode Penjualan:")
display(
    data[
        ['Metode Penjualan', 'Metode Bersih']
    ].head(15)
)

Perbandingan Metode Penjualan:

   Metode Penjualan Metode Bersih
0            Online        Online
1           Offline       Offline
2            Online        Online
3           offline       Offline
4            Online        Online
5            Online        Online
6           Offline       Offline
7            online        Online
8           Offline       Offline
9            Online        Online
10           Online        Online
11          Offline       Offline
12           online        Online
13          Offline       Offline
14           Online        Online

13. Menemukan Data yang Sama

In [22]:
print("\nData yang Diduga Mengalami Pengulangan:")

duplicate_rows = data[
    data.duplicated(
        subset=[
            'Produk Bersih',
            'Warna Bersih',
            'Ukuran Bersih',
            'Tanggal Bersih'
        ],
        keep=False
    )
]

display(duplicate_rows)

Data yang Diduga Mengalami Pengulangan:

,No,Nama Produk,Warna,Ukuran,Harga (Rp),Jumlah Terjual,Tanggal,Status Pembayaran,Metode Penjualan,Produk Bersih,Warna Bersih,Ukuran Bersih,Harga Bersih,Jumlah Terjual Bersih,Tanggal Bersih,Pembayaran Bersih,Metode Bersih
3,4,Kemeja Flanel,Merah,L,110000.0,7,05 Jan 2026,Lunas,offline,Kemeja Flanel,Merah,L,1100000.0,7.0,NaT,Lunas,Offline
34,35,Kemeja Flanel,Merah,L,110000.0,5,NaN,Lunas,Online,Kemeja Flanel,Merah,L,1100000.0,5.0,NaT,Lunas,Online

14. Mengurangi Data Berulang

In [23]:
data_deduplicated = data.drop_duplicates(
    subset=[
        'Produk Bersih',
        'Warna Bersih',
        'Ukuran Bersih',
        'Tanggal Bersih'
    ],
    keep='first'
)

data_deduplicated.reset_index(drop=True, inplace=True)

print("\nTotal Data Awal :", len(data))
print("Total Data Sesudah Pemeriksaan Duplikat :", len(data_deduplicated))

Total Data Awal : 35
Total Data Sesudah Pemeriksaan Duplikat : 34

15. Memeriksa Nilai yang Hilang

In [24]:
print("\nPengecekan Data Kosong:")
display(data_deduplicated.isnull().sum().to_frame('Jumlah Data Kosong'))

Pengecekan Data Kosong:

                       Jumlah Data Kosong
No                                      0
Nama Produk                             0
Warna                                   0
Ukuran                                  1
Harga (Rp)                              0
Jumlah Terjual                          0
Tanggal                                 0
Status Pembayaran                       0
Metode Penjualan                        0
Produk Bersih                           0
Warna Bersih                            0
Ukuran Bersih                           1
Harga Bersih                            1
Jumlah Terjual Bersih                   1
Tanggal Bersih                         17
Pembayaran Bersih                       0
Metode Bersih                           0

16. Mengatasi Harga yang Tidak Terisi

In [25]:
median_price = data_deduplicated['Harga Bersih'].median()

data_deduplicated['Harga Bersih'] = (
    data_deduplicated['Harga Bersih']
    .fillna(median_price)
)

print("\nJumlah Data Harga yang Masih Kosong:")
print(data_deduplicated['Harga Bersih'].isnull().sum())

Jumlah Data Harga yang Masih Kosong:
0

/tmp/ipykernel_3446/3916465482.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_deduplicated['Harga Bersih'] = (

17. Melengkapi Jumlah Penjualan

In [26]:
median_quantity = data_deduplicated['Jumlah Terjual Bersih'].median()

data_deduplicated['Jumlah Terjual Bersih'] = (
    data_deduplicated['Jumlah Terjual Bersih']
    .fillna(median_quantity)
)

print("\nJumlah Data Penjualan yang Masih Kosong:")
print(
    data_deduplicated['Jumlah Terjual Bersih'].isnull().sum()
)

Jumlah Data Penjualan yang Masih Kosong:
0

/tmp/ipykernel_3446/1961371459.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_deduplicated['Jumlah Terjual Bersih'] = (

18. Melengkapi Ukuran dan Tanggal

In [27]:
if data_deduplicated['Ukuran Bersih'].isnull().any():
    mode_size = data_deduplicated['Ukuran Bersih'].mode()[0]

    data_deduplicated['Ukuran Bersih'] = (
        data_deduplicated['Ukuran Bersih']
        .fillna(mode_size)
    )


if data_deduplicated['Tanggal Bersih'].isnull().any():
    mode_date = data_deduplicated['Tanggal Bersih'].mode()[0]

    data_deduplicated['Tanggal Bersih'] = (
        data_deduplicated['Tanggal Bersih']
        .fillna(mode_date)
    )

print("\nSisa Data Kosong pada Ukuran:")
print(data_deduplicated['Ukuran Bersih'].isnull().sum())

print("\nSisa Data Kosong pada Tanggal:")
print(data_deduplicated['Tanggal Bersih'].isnull().sum())

Sisa Data Kosong pada Ukuran:
0

Sisa Data Kosong pada Tanggal:
0

/tmp/ipykernel_3446/2561120011.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_deduplicated['Ukuran Bersih'] = (
/tmp/ipykernel_3446/2561120011.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_deduplicated['Tanggal Bersih'] = (

19. Melengkapi Data Kategori

In [28]:
if data_deduplicated['Warna Bersih'].isnull().any():
    mode_color = data_deduplicated['Warna Bersih'].mode()[0]

    data_deduplicated['Warna Bersih'] = (
        data_deduplicated['Warna Bersih']
        .fillna(mode_color)
    )


if data_deduplicated['Pembayaran Bersih'].isnull().any():
    mode_payment = data_deduplicated[
        'Pembayaran Bersih'
    ].mode()[0]

    data_deduplicated['Pembayaran Bersih'] = (
        data_deduplicated['Pembayaran Bersih']
        .fillna(mode_payment)
    )


if data_deduplicated['Metode Bersih'].isnull().any():
    mode_method = data_deduplicated[
        'Metode Bersih'
    ].mode()[0]

    data_deduplicated['Metode Bersih'] = (
        data_deduplicated['Metode Bersih']
        .fillna(mode_method)
    )


print("\nPemeriksaan Missing Value Terakhir:")
display(data_deduplicated.isnull().sum().to_frame('Jumlah Data Kosong'))

Pemeriksaan Missing Value Terakhir:

                       Jumlah Data Kosong
No                                      0
Nama Produk                             0
Warna                                   0
Ukuran                                  1
Harga (Rp)                              0
Jumlah Terjual                          0
Tanggal                                 0
Status Pembayaran                       0
Metode Penjualan                        0
Produk Bersih                           0
Warna Bersih                            0
Ukuran Bersih                           0
Harga Bersih                            0
Jumlah Terjual Bersih                   0
Tanggal Bersih                          0
Pembayaran Bersih                       0
Metode Bersih                           0

20. Menampilkan Dataset yang Sudah Dibersihkan

In [29]:
hasil_cleansing = data_deduplicated[
    [
        'No',
        'Produk Bersih',
        'Warna Bersih',
        'Ukuran Bersih',
        'Harga Bersih',
        'Jumlah Terjual Bersih',
        'Tanggal Bersih',
        'Pembayaran Bersih',
        'Metode Bersih'
    ]
]

print("\n====================================================")
print("DATA PENJUALAN BAJU DISTRO SETELAH DIBERSIHKAN")
print("====================================================")

display(hasil_cleansing)

====================================================
DATA PENJUALAN BAJU DISTRO SETELAH DIBERSIHKAN
====================================================

,No,Produk Bersih,Warna Bersih,Ukuran Bersih,Harga Bersih,Jumlah Terjual Bersih,Tanggal Bersih,Pembayaran Bersih,Metode Bersih
0,1,Kaos Oversize,Hitam,M,750000.0,12.0,2026-01-02,Lunas,Online
1,2,Kaos Oversize,Putih,L,750000.0,8.0,2026-01-02,Lunas,Offline
2,3,Hoodie Basic,Abu-abu,XL,1250000.0,5.0,2026-01-02,Belum Lunas,Online
3,4,Kemeja Flanel,Merah,L,1100000.0,7.0,2026-01-02,Lunas,Offline
4,5,Kaos Graphic,Hitam,M,850000.0,15.0,2026-01-02,Lunas,Online
5,6,Crewneck,Navy,L,1350000.0,6.0,2026-01-02,Belum Lunas,Online
6,7,Celana Cargo,Cream,32,1500000.0,4.0,2026-01-08,Lunas,Offline
7,8,Kaos Oversize,Hitam,M,750000.0,10.0,2026-01-09,Lunas,Online
8,9,Hoodie Basic,Hitam,XXL,1250000.0,3.0,2026-01-02,Belum Lunas,Offline
9,10,Kemeja Flanel,Biru,M,1100000.0,9.0,2026-01-11,Lunas,Online
10,11,Kaos Graphic,Putih,L,850000.0,11.0,2026-01-02,Lunas,Online
11,12,Crewneck,Navy,XL,1350000.0,7.0,2026-01-13,Belum Lunas,Offline
12,13,Celana Cargo,Hitam,30,1500000.0,5.0,2026-01-02,Lunas,Online
13,14,Kaos Oversize,Putih,XL,750000.0,14.0,2026-01-15,Lunas,Offline
14,15,Hoodie Basic,Abu-abu,L,1250000.0,6.0,2026-01-16,Belum Lunas,Online
15,16,Kemeja Flanel,Hijau,M,1100000.0,8.0,2026-01-02,Lunas,Offline
16,17,Kaos Graphic,Hitam,XL,850000.0,13.0,2026-01-18,Lunas,Online
17,18,Crewneck,Navy,M,1350000.0,4.0,2026-01-02,Belum Lunas,Online
18,19,Celana Cargo,Cream,34,1500000.0,3.0,2026-01-02,Lunas,Offline
19,20,Kaos Oversize,Hitam,L,750000.0,9.0,2026-01-02,Lunas,Online
20,21,Hoodie Basic,Hitam,M,1250.0,5.0,2026-01-22,Belum Lunas,Offline
21,22,Kemeja Flanel,Merah,XL,1100000.0,6.0,2026-01-23,Lunas,Online
22,23,Kaos Graphic,Putih,M,850000.0,12.0,2026-01-02,Lunas,Online
23,24,Crewneck,Navy,L,1350000.0,5.0,2026-01-25,Belum Lunas,Offline
24,25,Celana Cargo,Hitam,32,1500000.0,7.0,2026-01-02,Lunas,Online
25,26,Kaos Oversize,Hitam,XL,750000.0,16.0,2026-01-27,Lunas,Offline
26,27,Hoodie Basic,Abu-abu,L,1250000.0,4.0,2026-01-02,Belum Lunas,Online
27,28,Kemeja Flanel,Biru,M,1100000.0,10.0,2026-01-29,Lunas,Online
28,29,Kaos Graphic,Hitam,L,850000.0,9.0,2026-01-30,Lunas,Offline
29,30,Crewneck,Navy,XL,1350000.0,6.0,2026-01-02,Belum Lunas,Online
30,31,Kaos Oversize,Putih,L,750000.0,8.0,2026-01-02,Lunas,Online
31,32,Hoodie Basic,Hitam,M,1100000.0,2.0,2026-02-01,Belum Lunas,Offline
32,33,Kaos Graphic,Hitam,L,850000.0,10.0,2026-02-02,Lunas,Online
33,34,Celana Cargo,Cream,32,1500000.0,7.0,2026-02-03,Lunas,Offline

21. Cek Missing Value Setelah Cleansing

In [30]:
print("\nMissing Value Setelah Data Cleansing:")
print(hasil_cleansing.isnull().sum())

Missing Value Setelah Data Cleansing:
No                       0
Produk Bersih            0
Warna Bersih             0
Ukuran Bersih            0
Harga Bersih             0
Jumlah Terjual Bersih    0
Tanggal Bersih           0
Pembayaran Bersih        0
Metode Bersih            0
dtype: int64

22. Jumlah Data Terakhir

In [31]:
print("\nJumlah Data Awal :", len(data))
print("Jumlah Data Akhir:", len(hasil_cleansing))

Jumlah Data Awal : 35
Jumlah Data Akhir: 34

21. Mengekspor Hasil ke Excel

In [33]:
output_path = '/content/drive/MyDrive/Colab Notebooks/Data Bersih Penjualan Baju Distro.xlsx'

hasil_cleansing.to_excel(
    output_path,
    index=False,
    sheet_name='Data Bersih'
)

print("\nFile data bersih berhasil dibuat.")
print("Lokasi file:")
print(output_path)

File data bersih berhasil dibuat.
Lokasi file:
/content/drive/MyDrive/Colab Notebooks/Data Bersih Penjualan Baju Distro.xlsx